# Generated by Django 2.2.4 on 2019-08-28 23:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='First Name')),
                ('last_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Last Name')),
                ('username', models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Password')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_registration', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
